//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import "XfttsFluttifyPlugin.h"

NS_ASSUME_NONNULL_BEGIN

@interface XfttsFluttifyPlugin (SubHandler0)
- (NSDictionary<NSString*, Handler>*) getSubHandler0;
@end

NS_ASSUME_NONNULL_END
