//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_iflytek_speech_aidl_ISpeechRecognizer on java_lang_Object {
  

  

  @mustCallSuper
  Future<void> startListening(android_content_Intent var1, com_iflytek_speech_RecognizerListener var2) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('startListening::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> stopListening(com_iflytek_speech_RecognizerListener var1) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('stopListening::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> cancel(com_iflytek_speech_RecognizerListener var1) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('cancel::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> isListening() {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('isListening::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> buildGrammar(android_content_Intent var1, com_iflytek_speech_GrammarListener var2) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('buildGrammar::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> updateLexicon(android_content_Intent var1, com_iflytek_speech_LexiconListener var2) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('updateLexicon::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> writeAudio(android_content_Intent var1, Uint8List var2, int var3, int var4) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('writeAudio::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}