//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_iflytek_speech_aidl_ISpeakerVerifier on java_lang_Object {
  

  

  @mustCallSuper
  Future<int> verify(String var1, String var2, com_iflytek_speech_VerifierListener var3) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('verify::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> register(String var1, String var2, com_iflytek_speech_VerifierListener var3) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('register::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> endSpeak() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('endSpeak::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> stopSpeak() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('stopSpeak::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> setParameter(String var1, String var2) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('setParameter::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<String> getParameter(String var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getParameter::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}