//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_iflytek_speech_aidl_ITextUnderstander on java_lang_Object {
  

  

  @mustCallSuper
  Future<void> understandText(android_content_Intent var1, com_iflytek_speech_TextUnderstanderListener var2) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('understandText::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> cancel(com_iflytek_speech_TextUnderstanderListener var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('cancel::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> isUnderstanding() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('isUnderstanding::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}