//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin IFlySpeechRecognizerDelegate on NSObject {
  

  

  @mustCallSuper
  Future<void> onCompleted(IFlySpeechError errorCode) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onCompleted::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onResultsIsLast(List<NSObject> results, bool isLast) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onResultsIsLast::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onVolumeChanged(int volume) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onVolumeChanged::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onBeginOfSpeech() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onBeginOfSpeech::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onEndOfSpeech() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onEndOfSpeech::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onCancel() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onCancel::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onEventArg0arg1data(int eventType, int arg0, int arg1, NSData eventData) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onEventArg0arg1data::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}