// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class com_iflytek_speech_VerifierResult extends java_lang_Object with android_os_Parcelable {
  //region constants
  static const String name__ = 'com.iflytek.speech.VerifierResult';

  
  //endregion

  //region creators
  static Future<com_iflytek_speech_VerifierResult> create__String(String var1) async {
    final int refId = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('ObjectFactory::createcom_iflytek_speech_VerifierResult__String', {"var1": var1});
    final object = com_iflytek_speech_VerifierResult()..refId = refId..tag__ = 'xftts_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<com_iflytek_speech_VerifierResult>> create_batch__String(List<String> var1) async {
    if (false) {
      return Future.error('all args must have same length!');
    }
    final List resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('ObjectFactory::create_batchcom_iflytek_speech_VerifierResult__String', [for (int __i__ = 0; __i__ < var1.length; __i__++) {"var1": var1[__i__]}]);
  
    final List<com_iflytek_speech_VerifierResult> typedResult = resultBatch.map((result) => com_iflytek_speech_VerifierResult()..refId = result..tag__ = 'xftts_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  Future<String> get_sst() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_sst", {'refId': refId});
  
    return __result__;
  }
  
  Future<bool> get_ret() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_ret", {'refId': refId});
  
    return __result__;
  }
  
  Future<String> get_dcs() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_dcs", {'refId': refId});
  
    return __result__;
  }
  
  Future<String> get_vid() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_vid", {'refId': refId});
  
    return __result__;
  }
  
  Future<int> get_suc() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_suc", {'refId': refId});
  
    return __result__;
  }
  
  Future<int> get_rgn() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_rgn", {'refId': refId});
  
    return __result__;
  }
  
  Future<String> get_trs() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_trs", {'refId': refId});
  
    return __result__;
  }
  
  Future<String> get_source() async {
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_source", {'refId': refId});
  
    return __result__;
  }
  
  //endregion

  //region setters
  Future<void> set_sst(String sst) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_sst', {'refId': refId, "sst": sst});
  
  
  }
  
  Future<void> set_ret(bool ret) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_ret', {'refId': refId, "ret": ret});
  
  
  }
  
  Future<void> set_dcs(String dcs) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_dcs', {'refId': refId, "dcs": dcs});
  
  
  }
  
  Future<void> set_vid(String vid) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_vid', {'refId': refId, "vid": vid});
  
  
  }
  
  Future<void> set_suc(int suc) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_suc', {'refId': refId, "suc": suc});
  
  
  }
  
  Future<void> set_rgn(int rgn) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_rgn', {'refId': refId, "rgn": rgn});
  
  
  }
  
  Future<void> set_trs(String trs) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_trs', {'refId': refId, "trs": trs});
  
  
  }
  
  Future<void> set_source(String source) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_source', {'refId': refId, "source": source});
  
  
  }
  
  //endregion

  //region methods
  
  Future<String> getResultString() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.iflytek.speech.VerifierResult@$refId::getResultString([])');
    }
  
    // invoke native method
    final __result__ = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::getResultString', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (__result__ == null) {
      return null;
    } else {
      final __return__ = __result__;
    
      return __return__;
    }
  }
  
  //endregion
}

extension com_iflytek_speech_VerifierResult_Batch on List<com_iflytek_speech_VerifierResult> {
  //region getters
  Future<List<String>> get_sst_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_sst_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<bool>> get_ret_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_ret_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<bool>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_dcs_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_dcs_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_vid_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_vid_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_suc_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_suc_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_rgn_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_rgn_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<int>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_trs_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_trs_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  Future<List<String>> get_source_batch() async {
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.speech.VerifierResult::get_source_batch", [for (final __item__ in this) {'refId': __item__.refId}]);
    final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
  
    return typedResult;
  }
  
  //endregion

  //region setters
  Future<void> set_sst_batch(List<String> sst) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_sst_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "sst": sst[__i__]}]);
  
  
  }
  
  Future<void> set_ret_batch(List<bool> ret) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_ret_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "ret": ret[__i__]}]);
  
  
  }
  
  Future<void> set_dcs_batch(List<String> dcs) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_dcs_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "dcs": dcs[__i__]}]);
  
  
  }
  
  Future<void> set_vid_batch(List<String> vid) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_vid_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "vid": vid[__i__]}]);
  
  
  }
  
  Future<void> set_suc_batch(List<int> suc) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_suc_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "suc": suc[__i__]}]);
  
  
  }
  
  Future<void> set_rgn_batch(List<int> rgn) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_rgn_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "rgn": rgn[__i__]}]);
  
  
  }
  
  Future<void> set_trs_batch(List<String> trs) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_trs_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "trs": trs[__i__]}]);
  
  
  }
  
  Future<void> set_source_batch(List<String> source) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::set_source_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'refId': this[__i__].refId, "source": source[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  Future<List<String>> getResultString_batch() async {
    if (false) {
      return Future.error('all args must have same length!');
    }
  
    // invoke native method
    final resultBatch = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.speech.VerifierResult::getResultString_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"refId": this[__i__].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).cast<String>().map((__result__) => __result__).toList();
    
      return typedResult;
    }
  }
  
  //endregion
}