//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_iflytek_speech_VerifierListener on java_lang_Object {
  

  

  @mustCallSuper
  Future<void> onVolumeChanged(int var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onVolumeChanged::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onBeginOfSpeech() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onBeginOfSpeech::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onEndOfSpeech() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onEndOfSpeech::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onRegister(com_iflytek_speech_VerifierResult var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onRegister::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onEnd(com_iflytek_speech_VerifierResult var1, int var2) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onEnd::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onCancel() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onCancel::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<void> onError(int var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('onError::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}