//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_iflytek_msc_MetaVAD_Instance extends java_lang_Object  {
  // generate getters
  Future<int> get_handle() async {
    final result = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.msc.MetaVAD.Instance::get_handle", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_rate() async {
    final result = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.msc.MetaVAD.Instance::get_rate", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_begin() async {
    final result = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.msc.MetaVAD.Instance::get_begin", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_end() async {
    final result = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.msc.MetaVAD.Instance::get_end", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_seg() async {
    final result = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.msc.MetaVAD.Instance::get_seg", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_volume() async {
    final result = await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod("com.iflytek.msc.MetaVAD.Instance::get_volume", {'refId': refId});
  
    return result;
  }
  

  // generate setters
  Future<void> set_handle(int handle) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.msc.MetaVAD.Instance::set_handle', {'refId': refId, "handle": handle});
  
  
  }
  
  Future<void> set_rate(int rate) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.msc.MetaVAD.Instance::set_rate', {'refId': refId, "rate": rate});
  
  
  }
  
  Future<void> set_begin(int begin) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.msc.MetaVAD.Instance::set_begin', {'refId': refId, "begin": begin});
  
  
  }
  
  Future<void> set_end(int end) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.msc.MetaVAD.Instance::set_end', {'refId': refId, "end": end});
  
  
  }
  
  Future<void> set_seg(int seg) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.msc.MetaVAD.Instance::set_seg', {'refId': refId, "seg": seg});
  
  
  }
  
  Future<void> set_volume(int volume) async {
    await MethodChannel('com.fluttify/xftts_fluttify').invokeMethod('com.iflytek.msc.MetaVAD.Instance::set_volume', {'refId': refId, "volume": volume});
  
  
  }
  

  // generate methods
  
}