//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:xftts_fluttify/src/ios/ios.export.g.dart';
import 'package:xftts_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_iflytek_msc_AIMIC_Listener on java_lang_Object {
  

  

  @mustCallSuper
  Future<void> onWakeupMsg(int var1, int var2, int var3, Uint8List var4, int var5, Uint8List var6, int var7, Uint8List var8, int var9) {
  
  
    if (!fluttifyLogEnabled) {
      debugPrint('onWakeupMsg::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}